String teachername = "Tess Løvgreen";// skriver string for at gemmer teksten "Tess Løvgreen". variabelnavnet er teacherName (starter medet lille bogstave og sætter med et stort)  
int daysInYear = 365;
String city= "København"; // String her for at difenere at københavn er en by
boolean isACtive= (true); // sætter boolean for kun kan have værdierne true eller false
int minutsInDay = 60*24; // en variable typen int for at beregne antallet af minutter i en dag (60 min. pr. time. gange 24 timer)
double deValue = 22.12; // bruger double her for det er en variabel af typen (decimaltal). 
String sum = "Hej, jeg heddder "+teachername; // her bruger jeg string for at kombinere "Hej, jeg heddder "+teachername
boolean isCompleted= false; // sætter boolean for kun kan have værdierne true eller false
double result = 2.2 + 33; // her bruger jeg double for at gemme resultat af summen af 2.2 og 3.3
char letter = 'S'; // bruger char for at gemme enkelte tegn "s" 
